jaffle_shop:
  target: redshift
  outputs:
    prod:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      user: "{{ env_var('REDSHIFT_USERNAME') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      port: 5439
      dbname: "{{ env_var('REDSHIFT_DATABASE') }}"
      schema:  "{{ env_var('REDSHIFT_SCHEMA') }}"
      threads: 4
      sslmode: verify-full